#!/bin/sh
# Standalone native TUN setup for ARM64 Keenetic, after Entware on USB.
# Generated by tools/build.ps1; no XKeen/Xray installation is required.
set -eu
umask 077
PATH=/opt/sbin:/opt/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
die() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }
phase() { printf '\n== %s ==\n' "$*"; }
mode=install; prepare=no; assets=''
while [ "$#" -gt 0 ]; do
 case "$1" in
  --check) mode=check;;
  --prepare) prepare=yes;;
  --offline) shift; [ "$#" -gt 0 ] || die '--offline requires an asset directory.'; assets=$1; [ -d "$assets" ] || die 'Offline asset directory missing.';;
  --help|-h) echo 'Usage: sh install-mihomo-tun.sh [--check] [--prepare] [--offline DIR]'; exit 0;;
  *) die 'Unknown option.';;
 esac
 shift
done
[ "$(id -u)" = 0 ] || die 'Run as root through Entware SSH.'
[ "$(uname -m)" = aarch64 ] || die 'Only ARM64/aarch64 is supported.'
command -v opkg >/dev/null || die 'Install Entware on USB manually first.'
command -v ndmc >/dev/null || die 'Keenetic firmware required.'
[ -w /opt/etc ] || die '/opt is not writable.'
free_kb=$(df -Pk /opt | awk 'NR==2 {print $4}')
[ "$free_kb" -ge 262144 ] || die 'Need at least 256 MiB free on the Entware USB filesystem.'
ram_kb=$(awk '/MemAvailable:/ {a=$2} /MemFree:/ {f=$2} /^Buffers:/ {b=$2} /^Cached:/ {c=$2} END {print a?a:f+b+c}' /proc/meminfo)
[ "$ram_kb" -ge 131072 ] || die 'Need at least 128 MiB currently available RAM (USB does not increase RAM).'
for utility in ip base64 sha256sum; do command -v "$utility" >/dev/null || die "Required command missing: $utility"; done
if [ -x /opt/etc/init.d/S05xkeen ] || [ -x /opt/etc/init.d/S24xray ] || [ -x /opt/etc/init.d/S24mihomo ]; then
 die 'An existing XKeen installation was found. Use clean Entware to avoid competing firewall/routing services.'
fi
if [ "$mode" = check ]; then
 echo "ARM64/Entware checks OK. Free disk: $free_kb KiB; available RAM: $ram_kb KiB."
 if [ -c /dev/net/tun ]; then echo '/dev/net/tun exists; actual TUN creation is checked during installation.'
 else echo '/dev/net/tun missing: installation will try modprobe tun; firmware TUN support is required.'; fi
 echo 'Plan: Mihomo v1.19.32 + MetaCubeXD v1.273.1 + native IPv4 TUN for selected IPv4/MAC devices.'
 command -v iptables >/dev/null || echo 'iptables will be installed from Entware.'
 echo 'No changes made.'
 exit 0
fi
if [ ! -c /dev/net/tun ]; then
 modprobe tun 2>/dev/null || true
 if [ ! -c /dev/net/tun ] && grep -q '[[:space:]]tun$' /proc/misc; then mkdir -p /dev/net; mknod /dev/net/tun c 10 200; fi
fi
[ -c /dev/net/tun ] || die 'Firmware TUN support missing. Enable/install the router TUN/VPN component, then rerun.'
exec 3<>/dev/tty || die 'Interactive SSH terminal required.'
tmp=$(mktemp -d /tmp/mihomo-setup.XXXXXX)
ok=no
cleanup() {
 stty echo <&3 2>/dev/null || true
 rm -rf "$tmp"
 if [ "$ok" != yes ]; then
  echo 'Setup did not finish. Diagnostics: /tmp/mihomo-tun/core.log. Rerun after fixing the error.' >&2
  echo 'If installed, mtun panel shows panel credentials; mtun stop disables TUN routing.' >&2
 fi
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' HUP TERM
prompt() { printf '%s' "$1" >&3; IFS= read -r answer <&3 || die 'Input cancelled.'; }
phase 'Subscription and client'
printf 'HTTPS subscription URL: ' >&3
stty -echo <&3
IFS= read -r url <&3 || die 'Input cancelled.'
stty echo <&3; printf '\n' >&3
case "$url" in https://?*) ;; *) die 'HTTPS URL required.';; esac
printf '%s\n' "$url" > "$tmp/source-url"
unset url
client_ip=''; mac=''
if [ "$prepare" != yes ]; then
 echo 'Choose the PC that should use TUN. Reserve its IPv4 in Keenetic DHCP.'
 ip -4 neigh show dev br0 2>/dev/null || true
 prompt 'PC IPv4 address (for example 192.168.1.50): '
 client_ip=$answer
fi
phase 'Entware dependencies'
if [ -z "$assets" ]; then opkg update; fi
opkg install curl ca-bundle jq tar gzip ip-full iptables conntrack cron coreutils-nohup
command -v iptables >/dev/null || die 'iptables installation failed.'
mkdir -p /opt/lib /opt/etc/mihomo-tun /opt/var/run /opt/etc/ndm/netfilter.d
__TUN_PAYLOADS__
chmod 755 /opt/sbin/mtun /opt/etc/init.d/S80mihomo-tun
chmod 600 /opt/lib/mtun-lib.sh
. /opt/lib/mtun-lib.sh
lan_ip=$(ip -4 addr show br0 | awk '/inet / {split($2,a,"/"); print a[1]; exit}')
mt_ipv4 "$lan_ip" || die 'Cannot identify LAN IPv4 on br0.'
if [ "$prepare" = yes ]; then
 if [ -f "$MT_HOME/clients" ]; then cp "$MT_HOME/clients" "$tmp/clients"; else : > "$tmp/clients"; fi
 echo 'Prepare mode: no new clients will be assigned to TUN.'
else
mt_ipv4 "$client_ip" || die 'Invalid client IPv4 address.'
ip -4 route get "$client_ip" | grep -q ' dev br0 ' || die 'Client must be on the main br0 LAN.'
[ "$client_ip" != "$lan_ip" ] || die 'Enter the PC address, not the router address.'
ping -c 1 -W 1 "$client_ip" >/dev/null 2>&1 || true
mac=$(ip -4 neigh show "$client_ip" dev br0 | awk '/lladdr/ {for(i=1;i<NF;i++) if($i=="lladdr") {print $(i+1); exit}}')
if [ -z "$mac" ]; then mac=$(awk -v target="$client_ip" '$1==target && $4!="00:00:00:00:00:00" {print $4; exit}' /proc/net/arp); fi
prompt "PC MAC address [$mac]: "
mac=${answer:-$mac}
printf '%s %s\n' "$client_ip" "$mac" > "$tmp/clients"
mt_validate_clients "$tmp/clients" || die 'Invalid client MAC address. Find it in Keenetic device details.'
fi
# Refuse routing-table collisions on first installation. Our own files identify
# a repeat installation, but no unrelated priority-100 rules are deleted.
if [ ! -f "$MT_HOME/config.json" ]; then
 [ -z "$(ip -4 route show table 2023 2>/dev/null)" ] || die 'Routing table 2023 is already in use.'
 if ip -4 rule show | grep -Eq '^100:'; then die 'Routing priority 100 is already in use.'; fi
fi
fetch() {
 if [ -n "$assets" ]; then
  cp "$assets/${1##*/}" "$2" || die 'Required offline archive missing.'
 else
  curl --noproxy '*' --proto '=https' --proto-redir '=https' -fLsS --connect-timeout 15 --max-time 240 "$1" -o "$2"
 fi
}
phase 'Verified Mihomo core and panel downloads'
fetch https://github.com/MetaCubeX/mihomo/releases/download/v1.19.32/mihomo-linux-arm64-v1.19.32.gz "$tmp/mihomo.gz"
echo "9dd862e28b46ff7d775f169cceebc28deccaa0a9e804237d421cd2571e0caba0  $tmp/mihomo.gz" | sha256sum -c - >/dev/null || die 'Mihomo checksum mismatch.'
gzip -dc "$tmp/mihomo.gz" > /opt/sbin/mihomo-tun-core.new
chmod 755 /opt/sbin/mihomo-tun-core.new
/opt/sbin/mihomo-tun-core.new -v || die 'Mihomo cannot execute on this firmware.'
fetch https://github.com/MetaCubeX/metacubexd/releases/download/v1.273.1/compressed-dist.tgz "$tmp/ui.tgz"
echo "a178e00b67acabcda2dcef00afa90be6a7bb261e466a67dad58c8478d9553603  $tmp/ui.tgz" | sha256sum -c - >/dev/null || die 'Panel checksum mismatch.'
mkdir "$tmp/ui"
tar -xzf "$tmp/ui.tgz" -C "$tmp/ui"
[ -f "$tmp/ui/index.html" ] || die 'Invalid panel archive.'
phase 'Subscription download and isolated provider validation'
url=$(cat "$tmp/source-url")
if [ -n "$assets" ]; then
 cp "$assets/subscription.txt" "$tmp/subscription.txt" || die 'Offline subscription.txt missing.'
else
 curl --noproxy '*' --proto '=https' --proto-redir '=https' -fLsS --connect-timeout 15 --max-time 120 --max-filesize 4194304 "$url" > "$tmp/subscription.txt" 2> "$tmp/download.log" || die 'Subscription download failed. Initial installation requires normal internet.'
fi
unset url
backup="$MT_HOME/backup-$(date +%Y%m%d-%H%M%S)-$$"
mkdir "$backup"
for file in config.json clients subscription.txt source-url; do
 [ ! -f "$MT_HOME/$file" ] || cp -a "$MT_HOME/$file" "$backup/$file"
done
if [ -f "$MT_HOME/config.json" ]; then secret=$(jq -r '.secret' "$MT_HOME/config.json")
else secret=$(mt_random_secret); fi
[ -n "$secret" ] && [ "$secret" != null ] || die 'Invalid panel secret.'
mt_generate "$lan_ip" "$secret" true > "$tmp/config.json"
unset secret
mt_validate_provider "$tmp" /opt/sbin/mihomo-tun-core.new || die 'Subscription contains no usable Mihomo nodes. Existing service was not stopped.'
# Replace the binary only after its checksum, execution and provider checks. On a clean
# setup no running instance exists; on repeat stop the owned service first.
if mt_pid; then sh /opt/etc/init.d/S80mihomo-tun stop; fi
if [ -f /opt/sbin/mihomo-tun-core ]; then cp -a /opt/sbin/mihomo-tun-core "$backup/core"; fi
mv /opt/sbin/mihomo-tun-core.new /opt/sbin/mihomo-tun-core
phase 'Publish configuration and enable TUN'
for file in config.json clients subscription.txt source-url; do
 cp "$tmp/$file" "$MT_HOME/$file.new"; mv "$MT_HOME/$file.new" "$MT_HOME/$file"
done
if [ -d "$MT_HOME/ui" ]; then mv "$MT_HOME/ui" "$backup/ui"; fi
cp -a "$tmp/ui" "$MT_HOME/ui"
cat > /opt/etc/ndm/netfilter.d/100-mihomo-tun.sh <<'NETFILTER'
#!/bin/sh
/opt/etc/init.d/S80mihomo-tun firewall >/dev/null 2>&1 || logger -t mihomo-tun 'Cannot restore TUN firewall; run mtun check'
NETFILTER
chmod 755 /opt/etc/ndm/netfilter.d/100-mihomo-tun.sh
sh /opt/etc/init.d/S80mihomo-tun enable
# Flush only this PC's old conntrack sessions, not the entire home network.
if [ -n "$client_ip" ]; then conntrack -D -s "$client_ip" >/dev/null 2>&1 || true; fi
phase 'Select a working server'
mtun best || die 'No server passed HTTPS. TUN stays guarded; use the panel to select another server or mtun stop.'
mtun check
mkdir -p /opt/etc/cron.d
printf '* * * * * root /opt/etc/init.d/S80mihomo-tun guard >/dev/null 2>&1\n' > /opt/etc/cron.d/mihomo-tun
sh /opt/etc/init.d/S10cron start
pidof cron >/dev/null || die 'Entware cron did not start.'
sync
phase 'Ready'
mtun panel
if [ -n "$client_ip" ]; then echo "PC: $client_ip ($mac). Reserve this IPv4 address in Keenetic DHCP."
else echo 'No new PC assigned. Add one later: mtun clients IPv4 MAC'; fi
echo 'In MetaCubeXD, add the API address above and its Secret, then select PROXY.'
echo 'Commands: mtun list; mtun use NUMBER; mtun update; mtun change; mtun stop; mtun start.'
echo 'PC proxy/VPN settings stay unchanged. Corporate VPN compatibility must be checked on that PC.'
echo "Backups: $backup"
ok=yes
